[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "gunicorn borrowlogy.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 300 --log-level info --access-logfile - --error-logfile - --capture-output"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 