[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "gunicorn borrowlogy.wsgi:application --bind 0.0.0.0:$PORT -w 4 -t 4 --log-file - --access-logfile - --env PORT=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 