[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --settings=borrowlogy.settings_prod --noinput"

[deploy]
startCommand = "gunicorn borrowlogy.wsgi:application --env DJANGO_SETTINGS_MODULE=borrowlogy.settings_prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 