[build]
builder = "nixpacks"
buildCommand = "pip install django-filter==2.6.0 && python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn borrowlogy.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 