# Generated by Django 5.1.6 on 2025-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chemical_name", models.CharField(max_length=100)),
                ("mass", models.FloatField()),
                ("brand_name", models.CharField(max_length=100)),
                (
                    "hazard_type",
                    models.CharField(
                        choices=[
                            ("No GHS", "No GHS"),
                            ("Flammable", "Flammable"),
                            ("Harmful", "Harmful"),
                            ("Health Hazard", "Health Hazard"),
                            ("Acute Toxicity", "Acute Toxicity"),
                            ("Environmental Hazard", "Environmental Hazard"),
                        ],
                        default="No GHS",
                        max_length=20,
                    ),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "unique_together": {("chemical_name", "mass", "brand_name")},
            },
        ),
    ]
